### ISSUE TITLE
Is there no problem to use for torrentproject.se?

### ISSUE THREAD

**Issue by bangwall** [rmdashrf/go-cfscrape#2]
First time, I can use it to get informations through cloudflare but a few days ago, I received some error like can not find node..
So I install node library with using apt-get install node.
After that, I received exit 1 and cannot get any information from torrentproject.se.
Can any one help?

**Comment by rmdashrf** [comment]
sudo apt-get install nodejs

**Comment by bangwall** [comment]
I've done sudo apt-get install nodejs but still not working... 
The environment is raspbian jessie for raspberry PI one mode B.

**Comment by rmdashrf** [comment]
What is your output of `node --version`?

**Comment by bangwall** [comment]
I cannot see any information when using node --version or node -v.
But I can realize the version that was v0.10.29 when using nodejs --version.

**Comment by rmdashrf** [comment]
You probably have [this](https://packages.debian.org/jessie/node) installed.

Take a look at this [StackOverflow solution](http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04)

**Comment by bangwall** [comment]
YOU ARE THE BEST!!!

pi@raspberrypi:~/gowork/src/bwdrobogit/bangwall/torrent_downloader $ sudo ln -s /usr/bin/nodejs /usr/bin/node
pi@raspberrypi:~/gowork/src/bwdrobogit/bangwall/torrent_downloader $ ls
program.db  torrent_downloader.go
pi@raspberrypi:~/gowork/src/bwdrobogit/bangwall/torrent_downloader $ go run torrent_downloader.go testscrape http://torrentproject.se/ ?s=help
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
